// relay/worker.js — optional cloud relay for the phone remote, for networks
// where the phone can't reach the laptop at all (locked-down work machines,
// Wi-Fi client isolation). Same message protocol as the local relay in
// server.js, but rooms are keyed by a code so many games can share it:
//
//   phone /remote?room=CODE ──wss──▶ RelayRoom (one DO per code) ◀──wss── game tab
//
// Both sides connect OUTBOUND, so inbound firewalls never matter. The Worker
// also serves the static site (see wrangler.jsonc "assets"), so phones load
// the remote page straight from the public URL. Deploy: `npx wrangler deploy`.

import { DurableObject } from 'cloudflare:workers';
import { validateGame } from '../js/ai.js';

// The saved-games library lives in its own Durable Object class — see library.js.
export { Library } from './library.js';
// A game handed to students, addressed by a share code — see assign.js.
export { Assignment } from './assign.js';

// Share codes are read aloud and typed by students on Chromebooks, so they are
// short and use the same no-look-alike alphabet as the room codes. 8 characters
// of 31 is ~8.5e11 — far past guessing for a classroom word game, and the worst
// a guess could yield is a vocabulary round.
const CODE_ALPHABET = 'abcdefghjkmnpqrstuvwxyz23456789';
const CODE_LEN = 8;
const CODE_RE = /^[a-hjkm-np-z2-9]{8}$/;

function newCode() {
  const b = crypto.getRandomValues(new Uint8Array(CODE_LEN));
  return Array.from(b, (x) => CODE_ALPHABET[x % CODE_ALPHABET.length]).join('');
}

// Auth is a capability: the library key IS the address. sha256(key) names the
// Durable Object, so the raw key never appears in a URL or in observability
// logs, and there is no server-side secret to deploy. NEVER log the key itself.
const KEY_RE = /^[a-hjkm-np-z2-9]{26}$/; // as generated by the game; no look-alikes

// '*' rather than an allowlist on purpose: the game is opened from localhost, a
// LAN IP, workers.dev, GitHub Pages and file:// (which sends `Origin: null`, and
// no allowlist can match that). Safe because there are no cookies — nothing is
// sent by ambient authority, so there is nothing for a hostile page to abuse.
const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
  'Access-Control-Max-Age': '86400',
  'Cache-Control': 'no-store',
};

function bearerKey(request) {
  const m = (request.headers.get('Authorization') || '').match(/^Bearer\s+(.+)$/i);
  return (m ? m[1] : '').trim().toLowerCase();
}

async function sha256Hex(s) {
  const buf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(s));
  return [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, '0')).join('');
}

function corsJson(body, status) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS, 'Content-Type': 'application/json; charset=utf-8' },
  });
}

// Teacher side: create or revoke an assignment. Requires the library key, so a
// student — who only ever has a share code — can reach none of this.
async function handleAssign(request, env) {
  if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers: CORS });
  const key = bearerKey(request);
  if (!key) return corsJson({ error: 'Missing library key.' }, 401);
  if (!KEY_RE.test(key)) return corsJson({ error: 'That is not a library key.' }, 400);
  const ownerHash = await sha256Hex(key);

  if (request.method === 'DELETE') {
    const code = (new URL(request.url).searchParams.get('code') || '').toLowerCase();
    if (!CODE_RE.test(code)) return corsJson({ error: 'Bad code.' }, 400);
    const res = await env.ASSIGN.getByName(code).fetch(
      new Request('https://do/', { method: 'DELETE', body: JSON.stringify({ ownerHash }) }),
    );
    return corsJson(await res.json(), res.status);
  }

  if (request.method !== 'POST') return corsJson({ error: 'Method not allowed' }, 405);

  const body = await request.json().catch(() => null);
  if (!body || !body.game) return corsJson({ error: 'Expected { game, settings }.' }, 400);
  // Validate with the same function the editor uses, so an assignment can never
  // hand a class a round the game cannot actually play.
  const res = validateGame(body.game);
  if (!res.ok) return corsJson({ error: res.errors.slice(0, 3).join(' ') }, 400);

  // Only the two modes that work with nobody at the keyboard. voice-assist and
  // teacher-judge both wait for a teacher to press a key, so a student would sit
  // in front of a round that never advances.
  const mode = body.settings?.mode === 'voice-auto' ? 'voice-auto' : 'type-in';
  const durationSec = Math.max(0, Math.min(3600, Math.floor(Number(body.settings?.durationSec)) || 0));
  const strictness = typeof body.settings?.strictness === 'number' ? body.settings.strictness : 0.7;
  const days = Math.max(0, Math.min(365, Math.floor(Number(body.expiresInDays)) || 0));

  const doc = {
    ownerHash,
    title: res.game.title,
    game: res.game,
    settings: { mode, durationSec, strictness },
    createdAt: Date.now(),
    expiresAt: days ? Date.now() + days * 86400000 : null,
  };

  // Reusing a code re-points an existing link at a new round; otherwise mint one,
  // retrying the rare collision with someone else's assignment.
  const wanted = (body.code || '').toLowerCase();
  if (wanted && !CODE_RE.test(wanted)) return corsJson({ error: 'Bad code.' }, 400);
  for (let i = 0; i < 5; i++) {
    const code = wanted || newCode();
    const put = await env.ASSIGN.getByName(code).fetch(
      new Request('https://do/', { method: 'PUT', body: JSON.stringify({ ...doc, code }) }),
    );
    if (put.ok) return corsJson({ code, title: doc.title, settings: doc.settings, expiresAt: doc.expiresAt });
    if (wanted) return corsJson({ error: 'That code belongs to another library.' }, 409);
  }
  return corsJson({ error: 'Could not allocate a code; try again.' }, 503);
}

// Student side: a share code and nothing else. Read-only by construction — this
// handler has no way to write, and never sees or needs a library key.
async function handleAssignment(request, env) {
  if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers: CORS });
  if (request.method !== 'GET') return corsJson({ error: 'Method not allowed' }, 405);
  const code = (new URL(request.url).searchParams.get('code') || '').trim().toLowerCase();
  if (!CODE_RE.test(code)) return corsJson({ error: 'That code does not look right.' }, 400);
  const res = await env.ASSIGN.getByName(code).fetch(new Request('https://do/', { method: 'GET' }));
  return corsJson(await res.json(), res.status);
}

async function handleLibrary(request, env) {
  if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers: CORS });
  const key = bearerKey(request);
  if (!key) return corsJson({ error: 'Missing library key.' }, 401);
  // Check the shape BEFORE touching a Durable Object: junk keys must not be able
  // to spin up objects and burn the daily DO request budget the phone relay
  // shares — running out of that would kill the remote mid-lesson.
  if (!KEY_RE.test(key)) return corsJson({ error: 'That is not a library key.' }, 400);
  const res = await env.LIBRARY.getByName(await sha256Hex(key)).fetch(request);
  const out = new Response(res.body, res);
  for (const [k, v] of Object.entries(CORS)) out.headers.set(k, v);
  return out;
}

export class RelayRoom extends DurableObject {
  constructor(ctx, env) {
    super(ctx, env);
    // Answer link.js's keepalive pings at the edge, without waking a hibernated DO.
    ctx.setWebSocketAutoResponse(new WebSocketRequestResponsePair('{"t":"ping"}', '{"t":"pong"}'));
  }

  fetch(request) {
    // Role comes from the URL, not the hello message, so it can be a hibernation
    // tag — getWebSockets('host') then still works after the DO was evicted and
    // recreated around a sleeping socket.
    const role = new URL(request.url).searchParams.get('role') === 'host' ? 'host' : 'remote';
    const pair = new WebSocketPair();
    this.ctx.acceptWebSocket(pair[1], [role]);
    this.notifyPeers();
    return new Response(null, { status: 101, webSocket: pair[0] });
  }

  webSocketMessage(ws, raw) {
    if (typeof raw !== 'string') return;
    let msg;
    try {
      msg = JSON.parse(raw);
    } catch {
      return;
    }
    const role = this.ctx.getTags(ws)[0];
    // Forward the whole message verbatim, same as server.js — a per-field
    // whitelist has already silently dropped a new command's payload once.
    if (msg.t === 'cmd' && role === 'remote') this.broadcast('host', raw);
    else if (msg.t === 'state' && role === 'host') this.broadcast('remote', raw);
    // 'hello' is only meaningful to the local relay (role lives in the URL here).
  }

  webSocketClose(ws) {
    this.notifyPeers(ws);
  }

  webSocketError(ws) {
    this.notifyPeers(ws);
  }

  broadcast(tag, raw, except) {
    for (const ws of this.ctx.getWebSockets(tag)) {
      if (ws === except) continue;
      try {
        ws.send(raw);
      } catch {
        /* peer mid-close */
      }
    }
  }

  // `leaving` excludes a socket that is closing but may still be listed.
  notifyPeers(leaving) {
    const count = (tag) => this.ctx.getWebSockets(tag).filter((w) => w !== leaving).length;
    const msg = JSON.stringify({ t: 'peers', host: count('host') > 0, remotes: count('remote') });
    this.broadcast('host', msg, leaving);
    this.broadcast('remote', msg, leaving);
  }
}

export default {
  fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname === '/api/library') return handleLibrary(request, env);
    if (url.pathname === '/api/assign') return handleAssign(request, env);
    if (url.pathname === '/api/assignment') return handleAssignment(request, env);
    if (url.pathname === '/ws') {
      if ((request.headers.get('Upgrade') || '').toLowerCase() !== 'websocket') {
        // Plain GET: used by the game to probe "is this origin the relay?" (426
        // here vs 404 on a static host), and by humans poking around.
        return new Response('expected a websocket', { status: 426 });
      }
      const room = (url.searchParams.get('room') || '').toLowerCase();
      if (!/^[a-z0-9-]{1,32}$/.test(room)) return new Response('bad room', { status: 400 });
      return env.ROOMS.getByName(room).fetch(request);
    }
    // Static files are served by the assets layer before this runs; whatever
    // falls through (e.g. /lan-info, /tts) has no cloud equivalent — the game
    // detects that and falls back (browser voices, no LAN URL).
    return new Response('not found', { status: 404 });
  },
};
